[project]
name = "entelijanpy"
version = "0.1.0"
description = "Some useful python scripts"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "typer",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.14.8",
]

[project.scripts]
entelijanpy = "entelijanpy.main:app"